In [2]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()
type(iris)
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [3]:
x = iris.data
y = iris.target

from keras.utils import to_categorical

y = to_categorical(y)
print(y)
print(y.shape)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense,Dropout

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)
scaler = StandardScaler()

scaler.fit_transform(x_train)
scaler.transform(x_test)

model = Sequential()
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(8,activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(3,activation='softmax'))

model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

model.fit(x_train,y_train,epochs=1000,verbose=2)

c:\Users\Vaibhav\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:86: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_15 (Dense)                │ (None, 8)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_10 (Dropout)            │ (None, 8)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 8)              │            72 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_11 (Dropout)            │ (None, 8)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 3)              │            27 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 139 (556.00 B)

 Trainable params: 139 (556.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/1000
4/4 - 1s - 220ms/step - accuracy: 0.2833 - loss: 1.5750
Epoch 2/1000
4/4 - 0s - 7ms/step - accuracy: 0.2750 - loss: 1.5079
Epoch 3/1000
4/4 - 0s - 7ms/step - accuracy: 0.3333 - loss: 1.4097
Epoch 4/1000
4/4 - 0s - 8ms/step - accuracy: 0.3583 - loss: 1.2907
Epoch 5/1000
4/4 - 0s - 6ms/step - accuracy: 0.2833 - loss: 1.3140
Epoch 6/1000
4/4 - 0s - 8ms/step - accuracy: 0.2667 - loss: 1.3271
Epoch 7/1000
4/4 - 0s - 15ms/step - accuracy: 0.3583 - loss: 1.2033
Epoch 8/1000
4/4 - 0s - 7ms/step - accuracy: 0.3083 - loss: 1.1889
Epoch 9/1000
4/4 - 0s - 7ms/step - accuracy: 0.3667 - loss: 1.1273
Epoch 10/1000
4/4 - 0s - 7ms/step - accuracy: 0.5167 - loss: 1.0167
Epoch 11/1000
4/4 - 0s - 8ms/step - accuracy: 0.4500 - loss: 1.0996
Epoch 12/1000
4/4 - 0s - 7ms/step - accuracy: 0.4250 - loss: 1.1351
Epoch 13/1000
4/4 - 0s - 6ms/step - accuracy: 0.5583 - loss: 0.9774
Epoch 14/1000
4/4 - 0s - 7ms/step - accuracy: 0.6250 - loss: 0.9173
Epoch 15/1000
4/4 - 0s - 7ms/step - accuracy: 0.5167 -

In [10]:
predictions = np.argmax(model.predict(x_test),axis=1)
print(predictions)

print(np.argmax(y_test,axis=1))

from sklearn.metrics import confusion_matrix,classification_report
from keras.models import load_model

# code for saving the model

# new_model = load_model('myfirstmodel.h5')

print(confusion_matrix(y_test.argmax(axis=1),predictions))
print(classification_report(y_test.argmax(axis=1),predictions))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
[1 2 1 1 2 0 0 1 1 2 1 2 2 0 2 2 1 0 2 0 0 0 1 0 1 2 0 1 2 1]
[1 2 1 1 2 0 0 1 1 2 1 2 2 0 2 2 1 0 2 0 0 0 1 0 1 2 0 1 2 1]
[[ 9  0  0]
 [ 0 11  0]
 [ 0  0 10]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [25]:
def read_file(filepath):
    with open(filepath) as f:
        str_text = f.read()
    return str_text


In [27]:
import spacy

nlp = spacy.load('en_core_web_lg',disable=['parser','tagger','ner'])
nlp.max_length = 1198623

def seperate_punc(doc_text):
    return [token.text.lower() for token in nlp(doc_text) if token.text not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n ']

d = read_file(r'C:\Users\Vaibhav\OneDrive\Documents\FolderPython\Artificial_Intelligence\Natural_Language_Processing\Nlp_revision\06-Deep-Learning\moby_dick_four_chapters.txt')
tokens = seperate_punc(d)
tokens

c:\Users\Vaibhav\AppData\Local\Programs\Python\Python311\Lib\site-packages\spacy\pipeline\lemmatizer.py:211: UserWarning: [W108] The rule-based lemmatizer did not find POS annotation for one or more tokens. Check that your pipeline includes components that assign token.pos, typically 'tagger'+'attribute_ruler' or 'morphologizer'.
  warnings.warn(Warnings.W108)


['call',
 'me',
 'ishmael',
 'some',
 'years',
 'ago',
 'never',
 'mind',
 'how',
 'long',
 'precisely',
 'having',
 'little',
 'or',
 'no',
 'money',
 'in',
 'my',
 'purse',
 'and',
 'nothing',
 'particular',
 'to',
 'interest',
 'me',
 'on',
 'shore',
 'i',
 'thought',
 'i',
 'would',
 'sail',
 'about',
 'a',
 'little',
 'and',
 'see',
 'the',
 'watery',
 'part',
 'of',
 'the',
 'world',
 'it',
 'is',
 'a',
 'way',
 'i',
 'have',
 'of',
 'driving',
 'off',
 'the',
 'spleen',
 'and',
 'regulating',
 'the',
 'circulation',
 'whenever',
 'i',
 'find',
 'myself',
 'growing',
 'grim',
 'about',
 'the',
 'mouth',
 'whenever',
 'it',
 'is',
 'a',
 'damp',
 'drizzly',
 'november',
 'in',
 'my',
 'soul',
 'whenever',
 'i',
 'find',
 'myself',
 'involuntarily',
 'pausing',
 'before',
 'coffin',
 'warehouses',
 'and',
 'bringing',
 'up',
 'the',
 'rear',
 'of',
 'every',
 'funeral',
 'i',
 'meet',
 'and',
 'especially',
 'whenever',
 'my',
 'hypos',
 'get',
 'such',
 'an',
 'upper',
 'hand',
 '

In [29]:
train_len = 25+1

text_sequences = []

for i in range(train_len,len(tokens)):
    seq = tokens[i-train_len:i]
    text_sequences.append(seq)

type(text_sequences)
print(text_sequences[0])

print(' '.join(text_sequences[0]))
print(' '.join(text_sequences[1]))

['call', 'me', 'ishmael', 'some', 'years', 'ago', 'never', 'mind', 'how', 'long', 'precisely', 'having', 'little', 'or', 'no', 'money', 'in', 'my', 'purse', 'and', 'nothing', 'particular', 'to', 'interest', 'me', 'on']
call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on
me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore


In [32]:
from tensorflow.keras.preprocessing.text import Tokenizer

# initialize the tokenizer
tokenizer = Tokenizer()

# assuming text sequence is your list of text sequences
tokenizer.fit_on_texts(text_sequences)

# convert text sequences to numerical sequences
sequences = tokenizer.texts_to_sequences(text_sequences)

print(sequences)
print(tokenizer.index_word)

for i in sequences[0]:
    print(f'{i}:{tokenizer.index_word[i]}:word count {tokenizer.word_counts}')

[[956, 14, 263, 51, 261, 408, 87, 219, 129, 111, 954, 260, 50, 43, 38, 314, 7, 23, 546, 3, 150, 259, 6, 2713, 14, 24], [14, 263, 51, 261, 408, 87, 219, 129, 111, 954, 260, 50, 43, 38, 314, 7, 23, 546, 3, 150, 259, 6, 2713, 14, 24, 957], [263, 51, 261, 408, 87, 219, 129, 111, 954, 260, 50, 43, 38, 314, 7, 23, 546, 3, 150, 259, 6, 2713, 14, 24, 957, 5], [51, 261, 408, 87, 219, 129, 111, 954, 260, 50, 43, 38, 314, 7, 23, 546, 3, 150, 259, 6, 2713, 14, 24, 957, 5, 60], [261, 408, 87, 219, 129, 111, 954, 260, 50, 43, 38, 314, 7, 23, 546, 3, 150, 259, 6, 2713, 14, 24, 957, 5, 60, 5], [408, 87, 219, 129, 111, 954, 260, 50, 43, 38, 314, 7, 23, 546, 3, 150, 259, 6, 2713, 14, 24, 957, 5, 60, 5, 56], [87, 219, 129, 111, 954, 260, 50, 43, 38, 314, 7, 23, 546, 3, 150, 259, 6, 2713, 14, 24, 957, 5, 60, 5, 56, 315], [219, 129, 111, 954, 260, 50, 43, 38, 314, 7, 23, 546, 3, 150, 259, 6, 2713, 14, 24, 957, 5, 60, 5, 56, 315, 37], [129, 111, 954, 260, 50, 43, 38, 314, 7, 23, 546, 3, 150, 259, 6, 2713, 1

In [34]:
vocabulary_size = len(tokenizer.word_counts)
print(vocabulary_size)
print(type(sequences))

import numpy as np
sequences = np.array(sequences)
print(sequences)

2718
<class 'list'>
[[ 956   14  263 ... 2713   14   24]
 [  14  263   51 ...   14   24  957]
 [ 263   51  261 ...   24  957    5]
 ...
 [ 952   12  166 ...  262   53    2]
 [  12  166 2712 ...   53    2 2718]
 [ 166 2712    3 ...    2 2718   26]]


In [36]:
from keras.utils import to_categorical

x = sequences[:,:-1]
y = sequences[:,-1]
y = to_categorical(y,num_classes=vocabulary_size+1)

seq_len = x.shape[1]
seq_len

25

In [37]:
from keras.models import Sequential
from keras.layers import Dense,Dropout,LSTM,Embedding

def create_model(vocabulary_size,seq_len):
    model = Sequential()
    model.add(Embedding(vocabulary_size,25,input_length=seq_len))
    model.add(LSTM(150,return_sequences=True))
    model.add(LSTM(150))
    model.add(Dense(150,activation='relu'))
    model.add(Dense(vocabulary_size,activation='softmax'))
    model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
    model.summary()
    return model

model = create_model(vocabulary_size+1,seq_len)


c:\Users\Vaibhav\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\embedding.py:86: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [39]:
from pickle import dump,load

model.fit(x,y,batch_size=128,epochs=20,verbose=1)
model.save('my_mobydick_model.h5')
dump(tokenizer,open('my_simple_tokenizer','wb'))


Epoch 1/20
89/89 ━━━━━━━━━━━━━━━━━━━━ 7s 77ms/step - accuracy: 0.1063 - loss: 4.3336
Epoch 2/20
89/89 ━━━━━━━━━━━━━━━━━━━━ 8s 94ms/step - accuracy: 0.1018 - loss: 4.3006
Epoch 3/20
89/89 ━━━━━━━━━━━━━━━━━━━━ 10s 110ms/step - accuracy: 0.1032 - loss: 4.2683
Epoch 4/20
89/89 ━━━━━━━━━━━━━━━━━━━━ 9s 97ms/step - accuracy: 0.1144 - loss: 4.1847
Epoch 5/20
89/89 ━━━━━━━━━━━━━━━━━━━━ 8s 93ms/step - accuracy: 0.1193 - loss: 4.1338
Epoch 6/20
89/89 ━━━━━━━━━━━━━━━━━━━━ 8s 94ms/step - accuracy: 0.1203 - loss: 4.0929
Epoch 7/20
89/89 ━━━━━━━━━━━━━━━━━━━━ 9s 96ms/step - accuracy: 0.1239 - loss: 4.0674
Epoch 8/20
89/89 ━━━━━━━━━━━━━━━━━━━━ 10s 112ms/step - accuracy: 0.1259 - loss: 4.0336
Epoch 9/20
89/89 ━━━━━━━━━━━━━━━━━━━━ 13s 149ms/step - accuracy: 0.1349 - loss: 3.9844
Epoch 10/20
89/89 ━━━━━━━━━━━━━━━━━━━━ 9s 103ms/step - accuracy: 0.1370 - loss: 3.9227
Epoch 11/20
89/89 ━━━━━━━━━━━━━━━━━━━━ 14s 156ms/step - accuracy: 0.1410 - loss: 3.9106
Epoch 12/20
89/89 ━━━━━━━━━━━━━━━━━━━━ 9s 104ms/step -

In [47]:
from keras.preprocessing.sequence import pad_sequences

def generate_text(model,tokenizer,seq_len,seed_text,num_gen_words):
    output_text = []
    input_text = seed_text

    for i in range(num_gen_words):
        encoded_text = tokenizer.texts_to_sequence([input_text])[0]
        pad_encoding = pad_sequences([encoded_text],maxlen=seq_len,truncating='pre')
        pred_probs = model.predict(pad_encoding,verbose=0)
        pred_word_ind = np.argmax(pred_probs,axis=-1)[0]
        pred_word = tokenizer.index_word.get(pred_word_ind,'')
        input_text += " "+pred_word
        output_text.append(pred_word)
        
    return ' '.join(output_text)


In [45]:
text_sequences[0]
import random 
random.seed(101)
random_pick = random.randint(0,len(text_sequences))

random_seed_text = text_sequences[random_pick]
seed_text = ' '.join(random_seed_text)
seed_text

"thought i to myself the man 's a human being just as i am he has just as much reason to fear me as i have"

In [48]:
generate_text(model,tokenizer,seq_len,seed_text=seed_text,num_gen_words=25)

AttributeError: 'Tokenizer' object has no attribute 'texts_to_sequence'